/**
 * DEVELOPMENT WEBPACK CONFIGURATION
 */

const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const AddAssetHtmlPlugin = require('add-asset-html-webpack-plugin');
const CircularDependencyPlugin = require('circular-dependency-plugin');

module.exports = require('./webpack.base.babel')({
  mode: 'development',

  // Add hot reloading in development
  entry: [
    require.resolve('react-app-polyfill/ie11'),
    'webpack-hot-middleware/client?reload=true',
    path.join(process.cwd(), 'app/app.js'), // Start with js/app.js
  ],

  // Don't use hashes in dev mode for better performance
  output: {
    filename: '[name].js',
    chunkFilename: '[name].chunk.js',
  },

  optimization: {
    splitChunks: {
      chunks: 'all',
    },
  },

  // Add development plugins
  plugins: [
    new webpack.HotModuleReplacementPlugin(), // Tell webpack we want hot reloading
    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: 'app/index.html',
    }),

    // AdminLTE JS dependencies
    new AddAssetHtmlPlugin({ filepath: require.resolve('../../node_modules/admin-lte/plugins/jquery-ui/jquery-ui.min.js') }),
    new AddAssetHtmlPlugin({ filepath: require.resolve('../../node_modules/admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js') }),
    new AddAssetHtmlPlugin({ filepath: require.resolve('../../node_modules/admin-lte/plugins/sparklines/sparkline.js') }),
    new AddAssetHtmlPlugin({ filepath: require.resolve('../../node_modules/admin-lte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }),
    new AddAssetHtmlPlugin({ filepath: require.resolve('../../node_modules/admin-lte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js') }),
    new AddAssetHtmlPlugin({ filepath: require.resolve('../../node_modules/admin-lte/dist/js/adminlte.js') }),

    new CircularDependencyPlugin({
      exclude: /a\.js|node_modules/, // exclude node_modules
      failOnError: false, // show a warning when there is a circular dependency
    }),
  ],

  // Emit a source map for easier debugging
  // See https://webpack.js.org/configuration/devtool/#devtool
  devtool: 'eval-source-map',

  performance: {
    hints: false,
  },
});
